language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids log

script:
  - bundle exec rspec

addons:
  code_climate:
    repo_token: d3d49b55abedc77746ee6f87ddc16ae72b56bb759507a593d085569b8cc6199f

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
