swagger: '2.0'

info:
  version: "0.1.0"
  title: DataCite Labs API
  description: |
    The DataCite Labs API is currently not suited for production use. Please contact DataCite support for more information.
  contact:
    name: DataCite Support
    email: support@datacite.org

paths:
  # This is a path endpoint. Change it.
  /works:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Work` objects. Queries the DataCite [MDS](https://mds.datacite.org). The following parameters also work with [DataCite Event Data](https://eventdata.datacite.org):

        * id
        * publisher-id
        * source-id (only Event Data)
        * relation-type-id (only Event Data)

        DataCite Event Data also contains DOI names from other DOI registration agencies, as well as resources
        without a DOI.

        The following optional query param determine the offset, size and sorting of the results returned:

        * offset
        * rows
        * sort

      # This is array of GET operation parameters:
      parameters:
        -
          name: q
          in: query
          description: Query string
          required: false
          type: string
        -
          name: id
          in: query
          description: Work ID
          required: false
          type: string
        -
          name: member-id
          in: query
          description: Member ID
          required: false
          type: string
        -
          name: publisher-id
          in: query
          description: Publisher ID
          required: false
          type: string
        -
          name: resource-type-id
          in: query
          description: Resource Type ID
          required: false
          type: string
        -
          name: source-id
          in: query
          description: Source ID
          required: false
          type: string
        -
          name: relation-type-id
          in: query
          description: Relation Type ID
          required: false
          type: string
        -
          name: offset
          in: query
          description: Result offset, defaults to **0**
          required: false
          type: number
        -
          name: rows
          in: query
          description: Size of returned array, defaults to **25**
          required: false
          type: number
        -
          name: sort
          in: query
          description: |
            Result sorting field, defaults to **score** when **q** parameter is used,
            **minted** otherwise
          required: false
          type: number
        -
          name: order
          in: query
          description: Sort order, defaults to **desc**
          required: false
          type: string

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfWorks
            type: array
            items:
              title: Work
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                container-title:
                  type: string
        404:
          description: Not found
